const actionTypes={
    bookActions:{
        GET_BOOK_START:"GET_BOOK_START",
        GET_BOOK_SUCCESS:"GET_BOOK_SUCCESS",
        GET_BOOK_FAIL:"GET_BOOK_FAIL",
        DELETE_BOOK_START:"DELETE_BOOK_START",
        DELETE_BOOK_SUCCESS:"DELETE_BOOK_SUCCESS",
        DELETE_BOOK_FAIL:"DELETE_BOOK_FAIL",
        ADD_BOOK:"ADD_BOOK",
        EDİT_BOOK:"EDİT_BOOK",
        DELETE_BOOKS_AFTER_DELETE:"DELETE_BOOKS_AFTER_DELETE"
    },
    categoryActions:{
        GET_CATEGORIES_START:"GET_CATEGORIES_START",
        GET_CATEGORIES_SUCCESS:"GET_CATEGORIES_SUCCESS",
        GET_CATEGORIES_FAIL:"GET_CATEGORIES_FAIL",
        ADD_CATEGORY:"ADD_CATEGORY",
        DELETE_CATEGORY:"DELETE_CATEGORY",
        EDİT_CATEGORY:"EDİT_CATEGORY"
    }
}

export default actionTypes